# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_processing_system7_0_0/first_zynq_system_processing_system7_0_0.xci
# IP: The module: 'first_zynq_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_processing_system7_0_0/first_zynq_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_processing_system7_0_0/first_zynq_system_processing_system7_0_0.xci
# IP: The module: 'first_zynq_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_processing_system7_0_0/first_zynq_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
