# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/first_zynq_system/first_zynq_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==first_zynq_system || ORIG_REF_NAME==first_zynq_system} -quiet] -quiet

# IP: bd/first_zynq_system/ip/first_zynq_system_processing_system7_0_0/first_zynq_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==first_zynq_system_processing_system7_0_0 || ORIG_REF_NAME==first_zynq_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/first_zynq_system/ip/first_zynq_system_axi_gpio_0_0/first_zynq_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==first_zynq_system_axi_gpio_0_0 || ORIG_REF_NAME==first_zynq_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/first_zynq_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==first_zynq_system_axi_smc_0 || ORIG_REF_NAME==first_zynq_system_axi_smc_0} -quiet] -quiet

# IP: bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==first_zynq_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==first_zynq_system_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/first_zynq_system_ooc.xdc
