# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/first_zynq_system_axi_smc_0.xci
# IP: The module: 'first_zynq_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/bd_5364.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_1/bd_5364_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_2/bd_5364_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_3/bd_5364_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_4/bd_5364_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_5/bd_5364_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_6/bd_5364_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_7/bd_5364_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_8/bd_5364_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_9/bd_5364_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_10/bd_5364_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_11/bd_5364_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_12/bd_5364_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_1/bd_5364_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_5/bd_5364_s00a2s_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_6/bd_5364_sarn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_7/bd_5364_srn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_8/bd_5364_sawn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_9/bd_5364_swn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_10/bd_5364_sbn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_11/bd_5364_m00s2a_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/first_zynq_system_axi_smc_0.xci
# IP: The module: 'first_zynq_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/bd_5364.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_1/bd_5364_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_2/bd_5364_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_3/bd_5364_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_4/bd_5364_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_5/bd_5364_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_6/bd_5364_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_7/bd_5364_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_8/bd_5364_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_9/bd_5364_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_10/bd_5364_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_11/bd_5364_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_12/bd_5364_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_1/bd_5364_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_5/bd_5364_s00a2s_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_6/bd_5364_sarn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_7/bd_5364_srn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_8/bd_5364_sawn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_9/bd_5364_swn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_10/bd_5364_sbn_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_11/bd_5364_m00s2a_0_ooc.xdc

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado/PROJECT/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
